package View;

import javax.swing.JOptionPane; //resource menggunakan JOptionPane

public class Dashboard extends javax.swing.JFrame {

    public Dashboard() {
        initComponents(); //method yang dihasilkan oleh NetBeans swing designer. Ini menjabarkan komponen dan menetapkan nilai defaultnya.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MenuItemDataPengguna = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemLogOut = new javax.swing.JMenuItem();
        MenuIdentitasPerusahaan = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuItemSatuanBarang = new javax.swing.JMenuItem();
        MenuItemDataBarang = new javax.swing.JMenuItem();
        MenuItemStokBarang = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setPreferredSize(new java.awt.Dimension(950, 734));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 578, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("© 2022 PT Jaya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel3)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 950, -1));

        jDesktopPane2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ptjayafix.png"))); // NOI18N
        jDesktopPane2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 580));

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 580));

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-48.png"))); // NOI18N
        MenuHome.setText("Home");
        MenuHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHomeMouseClicked(evt);
            }
        });
        MenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuHome);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-48.png"))); // NOI18N
        jMenu5.setText("Pengguna");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        MenuItemDataPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-document-16.png"))); // NOI18N
        MenuItemDataPengguna.setText("Data Pengguna");
        MenuItemDataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemDataPenggunaMouseClicked(evt);
            }
        });
        MenuItemDataPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataPenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemDataPengguna);
        jMenu5.add(jSeparator3);

        MenuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-log-out-16.png"))); // NOI18N
        MenuItemLogOut.setText("Log Out");
        MenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemLogOut);

        jMenuBar1.add(jMenu5);

        MenuIdentitasPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-office-building-32.png"))); // NOI18N
        MenuIdentitasPerusahaan.setText("Identitas Perusahaan");
        MenuIdentitasPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuIdentitasPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuIdentitasPerusahaanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuIdentitasPerusahaan);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-48.png"))); // NOI18N
        jMenu3.setText("Barang");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        MenuItemSatuanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-16.png"))); // NOI18N
        MenuItemSatuanBarang.setText("Satuan Barang");
        MenuItemSatuanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSatuanBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemSatuanBarang);

        MenuItemDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-inventory-16.png"))); // NOI18N
        MenuItemDataBarang.setText("Data Barang");
        MenuItemDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemDataBarang);

        MenuItemStokBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-goods-16.png"))); // NOI18N
        MenuItemStokBarang.setText("Stok Barang");
        MenuItemStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStokBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemStokBarang);

        jMenuBar1.add(jMenu3);

        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-profit-report-48.png"))); // NOI18N
        MenuLaporan.setText("Laporan");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuIdentitasPerusahaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuIdentitasPerusahaanMouseClicked
        new IdentitasPerusahaan().setVisible(true); //memunculkan JFrame IdentitasPerusahaan
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuIdentitasPerusahaanMouseClicked

    private void MenuItemDataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDataPenggunaMouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuItemDataPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaActionPerformed
        new DataPengguna().setVisible(true); //memunculkan JFrame DataPengguna
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuItemDataPenggunaActionPerformed

    private void MenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin Log Out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        //`->menampilkan pop up pertanyaan Apakah Anda ingin Log Out?
            if(response==JOptionPane.YES_OPTION){ //Jika memilih yes
                new Login().setVisible(true); //method yang membuat JFrame Login muncul di layar
                this.dispose(); //menutup JFrame Dashboard
            } else if(response==JOptionPane.NO_OPTION){ //Jika memilih no
                //tidak terjadi apa-apa
            } else if(response==JOptionPane.CLOSED_OPTION){ //Jika memilih closed
                //tidak terjadi apa-apa
            }
    }//GEN-LAST:event_MenuItemLogOutActionPerformed

    private void MenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHomeActionPerformed

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
        new Dashboard().setVisible(true); //Memunculkan JFrame Dashboard baru
        this.dispose(); //menutup JFrame Dashboard lama
    }//GEN-LAST:event_MenuHomeMouseClicked

    private void MenuItemSatuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSatuanBarangActionPerformed
        new SatuanBarang().setVisible(true); //Memunculkan JFrame SatuanBarang
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuItemSatuanBarangActionPerformed

    private void MenuItemDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataBarangActionPerformed
        new DataBarang().setVisible(true); //Memunculkan JFrame DataBarang
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuItemDataBarangActionPerformed

    private void MenuItemStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStokBarangActionPerformed
        new StokBarang().setVisible(true); //Memunculkan JFrame StokBarang
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuItemStokBarangActionPerformed

    private void MenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaporanMouseClicked
        new FrameReport().setVisible(true); //Memunculkan JFrame FrameReport
        this.dispose(); //menutup JFrame Dashboard
    }//GEN-LAST:event_MenuLaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true); //memunculkan JFrame Dashboard di layar
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuHome;
    private javax.swing.JMenu MenuIdentitasPerusahaan;
    private javax.swing.JMenuItem MenuItemDataBarang;
    private javax.swing.JMenuItem MenuItemDataPengguna;
    private javax.swing.JMenuItem MenuItemLogOut;
    private javax.swing.JMenuItem MenuItemSatuanBarang;
    private javax.swing.JMenuItem MenuItemStokBarang;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
