package View;

import Model.Koneksi; //menghubungkan class Koneksi dari package Model ke DataBarang.java
import java.sql.Connection; //resource menggunakan Connection
import java.sql.ResultSet; //resource menggunakan ResultSet
import java.sql.Statement; //resource menggunakan Statement
import javax.swing.JOptionPane; //resource menggunakan JOptionPane

public class DataBarang extends javax.swing.JFrame {
    
    Connection con; //membangun koneksi dengan sumber data
    Statement stm; //antarmuka yang mewakili pernyataan SQL
    ResultSet rs; //hasil Statement dari execute dan excuteQuery
    String kdsatuan, satuan, quantity; //variabel tambahan menampung combo box BoxKodeSatuan, BoxSatuan dan menampung spinner SpinQuantity

    public DataBarang() {
        initComponents(); //method yang dihasilkan oleh NetBeans swing designer. Ini menjabarkan komponen dan menetapkan nilai defaultnya.
        Koneksi DB = new Koneksi(); //objek dari package model class Koneksi
        DB.koneksi(); //method koneksi
        con = DB.con; //untuk membuat variabel con di JFrame DataBarang memiliki fungsi yang sama seperti di Koneksi.java
        stm = DB.stm; //untuk membuat variabel stm di JFrame DataBarang memiliki fungsi yang sama seperti di Koneksi.java
        
        updateComboBoxKodeSatuan(); //memanggil method updateComboBoxKodeSatuan() di public DataBarang
        updateComboBoxSatuanBarang(); //memanggil updateComboBoxSatuanBarang() di public DataBarang
    }
    
    public void updateComboBoxKodeSatuan(){ //mengubah value kd_satuan tbsatuanbarang menjadi bagian dari item BoxKodeSatuan
        String query = "SELECT * FROM tbsatuanbarang"; //mengambil value dari tbsatuanbarang
        try {
            java.sql.PreparedStatement pst = con.prepareStatement(query); //penggunaan objek PreparedStatement untuk eksekusi query SQL
            rs = pst.executeQuery(query); //eksekusi query, hasilnya ada di rs
            
            while (rs.next()) {  //Mengembalikan nilai berikutnya jika cocok dengan pola yang dibuat dari string yang ditentukan.              
                BoxKodeSatuan.addItem(rs.getString("kd_satuan")); //menambahkan semua value kd_satuan ke item BoxKodeSatuan
            }
        } catch (Exception e) { //jika try gagal
            JOptionPane.showMessageDialog(this, e.getMessage()); //menampilkan error dimana lewat showMessage
        }
    }
    
    public void updateComboBoxSatuanBarang(){
        String query = "SELECT * FROM tbsatuanbarang"; //mengambil value dari tbsatuanbarang
        try {
            java.sql.PreparedStatement pst = con.prepareStatement(query); //penggunaan objek PreparedStatement untuk eksekusi query SQL
            rs = pst.executeQuery(query); //eksekusi query, hasilnya ada di rs
            
            while (rs.next()) {  //Mengembalikan nilai berikutnya jika cocok dengan pola yang dibuat dari string yang ditentukan.                 
                BoxSatuan.addItem(rs.getString("satuan")); //menambahkan semua value satuan ke item BoxSatuan
            }
        } catch (Exception e) { //jika try gagal
            JOptionPane.showMessageDialog(this, e.getMessage()); //menampilkan error dimana lewat showMessage
        }
    }
    
    public void clear(){
        txtKodeBarang.setText(""); //membuat text field txtKodeBarang kosong
        txtNamaBarang.setText(""); //membuat text field txtNamaBarang kosong
        txtHargaBeli.setText(""); //membuat text field txtHargaBeli kosong
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtKodeBarang = new javax.swing.JTextField();
        SpinQuantity = new javax.swing.JSpinner();
        txtNamaBarang = new javax.swing.JTextField();
        BoxKodeSatuan = new javax.swing.JComboBox<>();
        BoxSatuan = new javax.swing.JComboBox<>();
        txtHargaBeli = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ButtonSave = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MenuItemDataPengguna = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemLogOut = new javax.swing.JMenuItem();
        MenuIdentitasPerusahaan = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuItemSatuanBarang = new javax.swing.JMenuItem();
        MenuItemDataBarang = new javax.swing.JMenuItem();
        MenuItemStokBarang = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("© 2022 PT Jaya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel3)
                .addContainerGap(369, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(97, 109, 126));

        jPanel2.setBackground(new java.awt.Color(98, 111, 120));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Input Data Barang : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        txtKodeBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kode : "));

        SpinQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantity"));

        txtNamaBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Nama Barang : "));

        BoxKodeSatuan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kode Satuan : "));

        BoxSatuan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Satuan Barang : "));

        txtHargaBeli.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Harga Beli : "));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKodeBarang)
                    .addComponent(txtNamaBarang)
                    .addComponent(BoxKodeSatuan, 0, 261, Short.MAX_VALUE)
                    .addComponent(BoxSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHargaBeli))
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BoxKodeSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BoxSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SpinQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );

        jPanel4.setBackground(new java.awt.Color(98, 111, 120));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Navigasi : ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        ButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-48.png"))); // NOI18N
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-broom-24.png"))); // NOI18N
        ButtonClear.setText("Clear");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(ButtonSave)
                .addGap(76, 76, 76)
                .addComponent(ButtonClear)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-48.png"))); // NOI18N
        MenuHome.setText("Home");
        MenuHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHomeMouseClicked(evt);
            }
        });
        MenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuHome);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-48.png"))); // NOI18N
        jMenu5.setText("Pengguna");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        MenuItemDataPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-document-16.png"))); // NOI18N
        MenuItemDataPengguna.setText("Data Pengguna");
        MenuItemDataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemDataPenggunaMouseClicked(evt);
            }
        });
        MenuItemDataPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataPenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemDataPengguna);
        jMenu5.add(jSeparator3);

        MenuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-log-out-16.png"))); // NOI18N
        MenuItemLogOut.setText("Log Out");
        MenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemLogOut);

        jMenuBar1.add(jMenu5);

        MenuIdentitasPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-office-building-32.png"))); // NOI18N
        MenuIdentitasPerusahaan.setText("Identitas Perusahaan");
        MenuIdentitasPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuIdentitasPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuIdentitasPerusahaanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuIdentitasPerusahaan);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-48.png"))); // NOI18N
        jMenu3.setText("Barang");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        MenuItemSatuanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-16.png"))); // NOI18N
        MenuItemSatuanBarang.setText("Satuan Barang");
        MenuItemSatuanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSatuanBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemSatuanBarang);

        MenuItemDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-inventory-16.png"))); // NOI18N
        MenuItemDataBarang.setText("Data Barang");
        MenuItemDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemDataBarang);

        MenuItemStokBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-goods-16.png"))); // NOI18N
        MenuItemStokBarang.setText("Stok Barang");
        MenuItemStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStokBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemStokBarang);

        jMenuBar1.add(jMenu3);

        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-profit-report-48.png"))); // NOI18N
        MenuLaporan.setText("Laporan");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        txtKodeBarang.getText(); //value txtKodeBarang
        txtNamaBarang.getText(); //value txtNamaBarang
        kdsatuan = BoxKodeSatuan.getSelectedItem().toString(); //mengubah item yang dipilih pada BoxKodeSatuan menjadi string ditampung oleh variabel kdsatuan
        satuan = BoxSatuan.getSelectedItem().toString(); //mengubah item yang dipilih pada BoxSatuan menjadi string, ditampung oleh variabel satuan
        txtHargaBeli.getText(); //value txtHaragaBeli
        quantity = SpinQuantity.getValue().toString(); //mengubah value spinQuantity menjadi string, ditampung oleh variabel quantity

        try {  
                String query = "insert into tbdatabarang" + "(kode, namabarang, kd_satuan, satuan, hargabeli, quantity)" 
                        + "values (?,?,?,?,?,?)";
                //syntax memasukkan value ke tbdatabarang 
                java.sql.PreparedStatement pst = con.prepareStatement(query); //penggunaan objek PreparedStatement untuk eksekusi query SQL

                pst.setString(1, txtKodeBarang.getText()); //kolom kode
                pst.setString(2, txtNamaBarang.getText()); //kolom namabarang
                pst.setString(3, kdsatuan); //kolom kd_satuan
                pst.setString(4, satuan); //kolom satuan
                pst.setString(5, txtHargaBeli.getText()); //kolom hargabeli
                pst.setString(6, quantity); //kolom quantity
                pst.executeUpdate(); //eksekusi pernyataan
                {
                    JOptionPane.showMessageDialog(null, "Save Succesfull"); //akan muncul pop up Save Successfull setelah proses insert selesai
                }
                clear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); //jika try tidak berhasil akan menampilkan pop up ERRORnya dimana
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        clear(); //membersihkan text field
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
        new Dashboard().setVisible(true); //memunculkan JFrame Dashboard
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuHomeMouseClicked

    private void MenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHomeActionPerformed

    private void MenuItemDataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDataPenggunaMouseClicked

    private void MenuItemDataPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaActionPerformed
        new DataPengguna().setVisible(true); //memunculkan JFrame DataPengguna baru
        this.dispose(); //menutup JFrame DataBarang lama
    }//GEN-LAST:event_MenuItemDataPenggunaActionPerformed

    private void MenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin Log Out?", "Confirm", JOptionPane.YES_NO_OPTION
                , JOptionPane.QUESTION_MESSAGE);
        //`->menampilkan pop up pertanyaan Apakah Anda ingin Log Out?
        if(response==JOptionPane.YES_OPTION){ //Jika memilih yes
            new Login().setVisible(true); //method yang membuat JFrame MenuAplikasi muncul di layar
            this.dispose(); //menutup JFrame DataBarang
        } else if(response==JOptionPane.NO_OPTION){ //Jika memilih no
            //tidak terjadi apa-apa
        } else if(response==JOptionPane.CLOSED_OPTION){ //Jika close
            //tidak terjadi apa-apa
        }
    }//GEN-LAST:event_MenuItemLogOutActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuIdentitasPerusahaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuIdentitasPerusahaanMouseClicked
        new IdentitasPerusahaan().setVisible(true); //memunculkan JFrame IdentitasPerusahaan
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuIdentitasPerusahaanMouseClicked

    private void MenuItemSatuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSatuanBarangActionPerformed
        new SatuanBarang().setVisible(true); //memunculkan JFrame SatuanBarang
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuItemSatuanBarangActionPerformed

    private void MenuItemDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataBarangActionPerformed
        new DataBarang().setVisible(true); //memunculkan JFrame DataBarang
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuItemDataBarangActionPerformed

    private void MenuItemStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStokBarangActionPerformed
        new StokBarang().setVisible(true); //memunculkan JFrame StokBarang
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuItemStokBarangActionPerformed

    private void MenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaporanMouseClicked
        new FrameReport().setVisible(true); //memunculkan JFrame FrameReport
        this.dispose(); //menutup JFrame DataBarang
    }//GEN-LAST:event_MenuLaporanMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarang().setVisible(true); //memunculkan JFrame DataBarang di layar
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxKodeSatuan;
    private javax.swing.JComboBox<String> BoxSatuan;
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JMenu MenuHome;
    private javax.swing.JMenu MenuIdentitasPerusahaan;
    private javax.swing.JMenuItem MenuItemDataBarang;
    private javax.swing.JMenuItem MenuItemDataPengguna;
    private javax.swing.JMenuItem MenuItemLogOut;
    private javax.swing.JMenuItem MenuItemSatuanBarang;
    private javax.swing.JMenuItem MenuItemStokBarang;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JSpinner SpinQuantity;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtKodeBarang;
    private javax.swing.JTextField txtNamaBarang;
    // End of variables declaration//GEN-END:variables
}
