package View;

import Model.Koneksi; //menghubungkan class Koneksi dari package Model ke FrameReport.java
import java.sql.Connection; //resource menggunakan Connection
import java.util.HashMap; //resource menggunakan HashMap
import javax.swing.JOptionPane; //resource menggunakan JOptionPane
import net.sf.jasperreports.engine.JasperCompileManager; //resource menggunakan JasperCompileManager
import net.sf.jasperreports.engine.JasperFillManager; //resource menggunakan JasperFillManager
import net.sf.jasperreports.engine.JasperPrint; //resource menggunakan JasperPrint
import net.sf.jasperreports.engine.JasperReport; //resource menggunakan JasperReport
import net.sf.jasperreports.engine.design.JasperDesign; //resource menggunakan JasperDesign
import net.sf.jasperreports.engine.xml.JRXmlLoader; //resource menggunakan JRXmlLoader
import net.sf.jasperreports.view.JasperViewer; //resource menggunakan JasperViewer

public class FrameReport extends javax.swing.JFrame {

    Connection con; //membangun koneksi dengan sumber data
    
    public FrameReport() {
        initComponents(); //method yang dihasilkan oleh NetBeans swing designer. Ini menjabarkan komponen dan menetapkan nilai defaultnya.
        Koneksi DB = new Koneksi(); //objek dari package model class Koneksi
        DB.koneksi(); //method koneksi
        con = DB.con; //untuk membuat variabel con di JFrame FrameReport memiliki fungsi yang sama seperti di Koneksi.java
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtfromkd = new javax.swing.JTextField();
        txttokd = new javax.swing.JTextField();
        ButtonCetak = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MenuItemDataPengguna = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemLogOut = new javax.swing.JMenuItem();
        MenuIdentitasPerusahaan = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuItemSatuanBarang = new javax.swing.JMenuItem();
        MenuItemDataBarang = new javax.swing.JMenuItem();
        MenuItemStokBarang = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Laporan");

        jPanel2.setBackground(new java.awt.Color(97, 109, 126));

        jPanel5.setBackground(new java.awt.Color(98, 111, 120));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ButtonCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-print-24.png"))); // NOI18N
        ButtonCetak.setText("Cetak");
        ButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCetakActionPerformed(evt);
            }
        });

        jLabel2.setText("Tampilkan Data Dari Kode: ");

        jLabel3.setText("Sampai Data Kode:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonCetak)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttokd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfromkd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfromkd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttokd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonCetak)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Laporan Stok Barang.png"))); // NOI18N
        jLabel1.setText("\\");

            jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
            jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
            jDesktopPane1.setLayout(jDesktopPane1Layout);
            jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
            jLabel4.setText("© 2022 PT Jaya");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(320, 320, 320)
                    .addComponent(jLabel4)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(jLabel4)
                    .addContainerGap(25, Short.MAX_VALUE))
            );

            MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-48.png"))); // NOI18N
            MenuHome.setText("Home");
            MenuHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
            MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    MenuHomeMouseClicked(evt);
                }
            });
            MenuHome.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuHomeActionPerformed(evt);
                }
            });
            jMenuBar1.add(MenuHome);

            jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-48.png"))); // NOI18N
            jMenu5.setText("Pengguna");
            jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
            jMenu5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenu5ActionPerformed(evt);
                }
            });

            MenuItemDataPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-document-16.png"))); // NOI18N
            MenuItemDataPengguna.setText("Data Pengguna");
            MenuItemDataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    MenuItemDataPenggunaMouseClicked(evt);
                }
            });
            MenuItemDataPengguna.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuItemDataPenggunaActionPerformed(evt);
                }
            });
            jMenu5.add(MenuItemDataPengguna);
            jMenu5.add(jSeparator3);

            MenuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-log-out-16.png"))); // NOI18N
            MenuItemLogOut.setText("Log Out");
            MenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuItemLogOutActionPerformed(evt);
                }
            });
            jMenu5.add(MenuItemLogOut);

            jMenuBar1.add(jMenu5);

            MenuIdentitasPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-office-building-32.png"))); // NOI18N
            MenuIdentitasPerusahaan.setText("Identitas Perusahaan");
            MenuIdentitasPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
            MenuIdentitasPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    MenuIdentitasPerusahaanMouseClicked(evt);
                }
            });
            jMenuBar1.add(MenuIdentitasPerusahaan);

            jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-48.png"))); // NOI18N
            jMenu3.setText("Barang");
            jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

            MenuItemSatuanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-16.png"))); // NOI18N
            MenuItemSatuanBarang.setText("Satuan Barang");
            MenuItemSatuanBarang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuItemSatuanBarangActionPerformed(evt);
                }
            });
            jMenu3.add(MenuItemSatuanBarang);

            MenuItemDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-inventory-16.png"))); // NOI18N
            MenuItemDataBarang.setText("Data Barang");
            MenuItemDataBarang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuItemDataBarangActionPerformed(evt);
                }
            });
            jMenu3.add(MenuItemDataBarang);

            MenuItemStokBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-goods-16.png"))); // NOI18N
            MenuItemStokBarang.setText("Stok Barang");
            MenuItemStokBarang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    MenuItemStokBarangActionPerformed(evt);
                }
            });
            jMenu3.add(MenuItemStokBarang);

            jMenuBar1.add(jMenu3);

            jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-profit-report-48.png"))); // NOI18N
            jMenu1.setText("Laporan");
            jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
            jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jMenu1MouseClicked(evt);
                }
            });
            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jDesktopPane1)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void ButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCetakActionPerformed
        String fromkd = txtfromkd.getText(); //menampung value txtfromkd pada variabel fromkd
        String tokd = txttokd.getText(); //menampung value txttokd pada variabel tokd
        
        HashMap a = new HashMap(); //menyimpan key dan value pair
        a.put("fromkd", fromkd);
        a.put("tokd", tokd);
        
        try{
            JasperDesign jDesign = JRXmlLoader.load("C:\\Users\\MSI Modern 14\\Documents\\NetBeansProjects\\UAS_31210053\\src\\View"
                    + "\\ReportStokBarang.jrxml");
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, a, con);
            JasperViewer.viewReport(jPrint);
        } catch(Exception e){ //Jika try error
            JOptionPane.showMessageDialog(null, e.getMessage()); //menampilkan errornya dimana lewat showMessage
        }
    }//GEN-LAST:event_ButtonCetakActionPerformed

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
        new Dashboard().setVisible(true); //memunculkan JFrame Dashboard
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuHomeMouseClicked

    private void MenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHomeActionPerformed

    private void MenuItemDataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDataPenggunaMouseClicked

    private void MenuItemDataPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaActionPerformed
       new DataPengguna().setVisible(true); //memunculkan JFrame DataPengguna
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuItemDataPenggunaActionPerformed

    private void MenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin Log Out?", "Confirm", JOptionPane.YES_NO_OPTION
                , JOptionPane.QUESTION_MESSAGE);
        //`->menampilkan pop up pertanyaan Apakah Anda ingin Log Out?
        if(response==JOptionPane.YES_OPTION){ //Jika memilih yes
            new Login().setVisible(true); //method yang membuat JFrame Login muncul di layar
            this.dispose(); //menutup JFrame FrameReport
        } else if(response==JOptionPane.NO_OPTION){ //Jika memilih no
            //tidak terjadi apa-apa
        } else if(response==JOptionPane.CLOSED_OPTION){ //Jika closed
            //tidak terjadi apa-apa
        }
    }//GEN-LAST:event_MenuItemLogOutActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuIdentitasPerusahaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuIdentitasPerusahaanMouseClicked
        new IdentitasPerusahaan().setVisible(true); //memunculkan JFrame IdentitasPerusahaan
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuIdentitasPerusahaanMouseClicked

    private void MenuItemSatuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSatuanBarangActionPerformed
        new SatuanBarang().setVisible(true); //memunculkan JFrame SatuanBarang
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuItemSatuanBarangActionPerformed

    private void MenuItemDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataBarangActionPerformed
        new DataBarang().setVisible(true); //memunculkan JFrame DataBarang
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuItemDataBarangActionPerformed

    private void MenuItemStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStokBarangActionPerformed
        new StokBarang().setVisible(true); //memunculkan JFrame StokBarang
        this.dispose(); //menutup JFrame FrameReport
    }//GEN-LAST:event_MenuItemStokBarangActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new FrameReport().setVisible(true); //memunculkan JFrame FrameReport baru
        this.dispose(); //menutup JFrame FrameReport lama
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameReport().setVisible(true); //memunculkan JFrame FrameReport di layar
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCetak;
    private javax.swing.JMenu MenuHome;
    private javax.swing.JMenu MenuIdentitasPerusahaan;
    private javax.swing.JMenuItem MenuItemDataBarang;
    private javax.swing.JMenuItem MenuItemDataPengguna;
    private javax.swing.JMenuItem MenuItemLogOut;
    private javax.swing.JMenuItem MenuItemSatuanBarang;
    private javax.swing.JMenuItem MenuItemStokBarang;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField txtfromkd;
    private javax.swing.JTextField txttokd;
    // End of variables declaration//GEN-END:variables
}
