package View;

import Model.Koneksi; //menghubungkan class Koneksi dari package Model ke DataBarang.java
import java.sql.Connection; //resource menggunakan Connection
import java.sql.ResultSet; //resource menggunakan ResultSet
import java.sql.Statement; //resource menggunakan Statement
import javax.swing.JOptionPane; //resource menggunakan JOptionPane

public class SatuanBarang extends javax.swing.JFrame {

    Connection con; //membangun koneksi dengan sumber data
    Statement stm; //antarmuka yang mewakili pernyataan SQL
    ResultSet rs; //hasil Statement dari execute dan excuteQuery
    
    public SatuanBarang() {
        initComponents(); //method yang dihasilkan oleh NetBeans swing designer. Ini menjabarkan komponen dan menetapkan nilai defaultnya.
        Koneksi DB = new Koneksi(); //objek dari package model class Koneksi
        DB.koneksi(); //method koneksi
        con = DB.con; //untuk membuat variabel con di JFrame SatuanBarang memiliki fungsi yang sama seperti di Koneksi.java
        stm = DB.stm; //untuk membuat variabel stm di JFrame SatuanBarang memiliki fungsi yang sama seperti di Koneksi.java
    }
    
    public void clear(){
        txtKd_Satuan.setText(""); //membuat text field txtKd_Satuan kosong
        txtSatuan.setText(""); //membuat text field txtSatuan kosong
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtKd_Satuan = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        ButtonClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuHome = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MenuItemDataPengguna = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuItemLogOut = new javax.swing.JMenuItem();
        MenuIdentitasPerusahaan = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuItemSatuanBarang = new javax.swing.JMenuItem();
        MenuItemDataBarang = new javax.swing.JMenuItem();
        MenuItemStokBarang = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Satuan Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("© 2022 PT Jaya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(97, 109, 126));

        jPanel3.setBackground(new java.awt.Color(98, 111, 120));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtKd_Satuan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Kode Satuan : "));
        txtKd_Satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKd_SatuanActionPerformed(evt);
            }
        });

        txtSatuan.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Satuan Barang : "));

        ButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-48.png"))); // NOI18N
        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-broom-24.png"))); // NOI18N
        ButtonClear.setText("Clear");
        ButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtKd_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonSave)
                .addGap(26, 26, 26)
                .addComponent(ButtonClear)
                .addGap(94, 94, 94))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKd_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PT Jaya.png"))); // NOI18N

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-home-48.png"))); // NOI18N
        MenuHome.setText("Home");
        MenuHome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHomeMouseClicked(evt);
            }
        });
        MenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuHome);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-48.png"))); // NOI18N
        jMenu5.setText("Pengguna");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        MenuItemDataPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-document-16.png"))); // NOI18N
        MenuItemDataPengguna.setText("Data Pengguna");
        MenuItemDataPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuItemDataPenggunaMouseClicked(evt);
            }
        });
        MenuItemDataPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataPenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemDataPengguna);
        jMenu5.add(jSeparator3);

        MenuItemLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-log-out-16.png"))); // NOI18N
        MenuItemLogOut.setText("Log Out");
        MenuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemLogOutActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemLogOut);

        jMenuBar1.add(jMenu5);

        MenuIdentitasPerusahaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-office-building-32.png"))); // NOI18N
        MenuIdentitasPerusahaan.setText("Identitas Perusahaan");
        MenuIdentitasPerusahaan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuIdentitasPerusahaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuIdentitasPerusahaanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuIdentitasPerusahaan);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-48.png"))); // NOI18N
        jMenu3.setText("Barang");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        MenuItemSatuanBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-box-16.png"))); // NOI18N
        MenuItemSatuanBarang.setText("Satuan Barang");
        MenuItemSatuanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSatuanBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemSatuanBarang);

        MenuItemDataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-inventory-16.png"))); // NOI18N
        MenuItemDataBarang.setText("Data Barang");
        MenuItemDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemDataBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemDataBarang);

        MenuItemStokBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-goods-16.png"))); // NOI18N
        MenuItemStokBarang.setText("Stok Barang");
        MenuItemStokBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemStokBarangActionPerformed(evt);
            }
        });
        jMenu3.add(MenuItemStokBarang);

        jMenuBar1.add(jMenu3);

        MenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-profit-report-48.png"))); // NOI18N
        MenuLaporan.setText("Laporan");
        MenuLaporan.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        MenuLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLaporanMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtKd_SatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKd_SatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKd_SatuanActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        txtKd_Satuan.getText(); //value txtKd_Satuan
        txtSatuan.getText(); //value txtSatuan

        try { 
                String query = "insert into tbsatuanbarang" + "(kd_satuan, satuan)" + "values (?,?)"; //syntax memasukkan value ke tbsatuanbarang 
                java.sql.PreparedStatement pst = con.prepareStatement(query); //penggunaan objek PreparedStatement untuk eksekusi query SQL

                pst.setString(1, txtKd_Satuan.getText()); //kolom kd_satuan
                pst.setString(2, txtSatuan.getText()); //kolom satuan
                pst.executeUpdate(); //eksekusi pernyataan
                {
                    JOptionPane.showMessageDialog(null, "Save Succesfull"); //akan muncul pop up Save Successfull setelah proses insert selesai
                }
                clear(); //membersihkan text field
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage()); //jika try tidak berhasil akan menampilkan pop up ERROR
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClearActionPerformed
        clear(); //membersihkan text field
    }//GEN-LAST:event_ButtonClearActionPerformed

    private void MenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHomeMouseClicked
        new Dashboard().setVisible(true); //memunculkan JFrame Dashboard
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuHomeMouseClicked

    private void MenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHomeActionPerformed

    private void MenuItemDataPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemDataPenggunaMouseClicked

    private void MenuItemDataPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataPenggunaActionPerformed
        new DataPengguna().setVisible(true); //memunculkan JFrame DataPengguna
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuItemDataPenggunaActionPerformed

    private void MenuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemLogOutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin Log Out?", "Confirm", JOptionPane.YES_NO_OPTION
                , JOptionPane.QUESTION_MESSAGE);
        //`->menampilkan pop up pertanyaan Apakah Anda ingin Log Out?
        if(response==JOptionPane.YES_OPTION){ //Jika memilih yes
            new Login().setVisible(true); //method yang membuat JFrame Login muncul di layar
            this.dispose(); //menutup JFrame SatuanBarang
        } else if(response==JOptionPane.NO_OPTION){ //Jika memilih no
            //tidak terjadi apa-apa
        } else if(response==JOptionPane.CLOSED_OPTION){ //Jika closed
            //tidak terjadi apa-apa
        }
    }//GEN-LAST:event_MenuItemLogOutActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void MenuIdentitasPerusahaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuIdentitasPerusahaanMouseClicked
        new IdentitasPerusahaan().setVisible(true); //memunculkan JFrame IdentitasPerusahaan
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuIdentitasPerusahaanMouseClicked

    private void MenuItemSatuanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSatuanBarangActionPerformed
        new SatuanBarang().setVisible(true); //memunculkan JFrame SatuanBarang baru
        this.dispose(); //menutup JFrame SatuanBarang lama
    }//GEN-LAST:event_MenuItemSatuanBarangActionPerformed

    private void MenuItemDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemDataBarangActionPerformed
        new DataBarang().setVisible(true); //memunculkan JFrame DataBarang
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuItemDataBarangActionPerformed

    private void MenuItemStokBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemStokBarangActionPerformed
        new StokBarang().setVisible(true); //memunculkan JFrame StokBarang
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuItemStokBarangActionPerformed

    private void MenuLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaporanMouseClicked
        new FrameReport().setVisible(true); //memunculkan JFrame Framereport
        this.dispose(); //menutup JFrame SatuanBarang
    }//GEN-LAST:event_MenuLaporanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SatuanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SatuanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SatuanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SatuanBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SatuanBarang().setVisible(true); //memunculkan JFrame SatuanBarang di layar
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClear;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JMenu MenuHome;
    private javax.swing.JMenu MenuIdentitasPerusahaan;
    private javax.swing.JMenuItem MenuItemDataBarang;
    private javax.swing.JMenuItem MenuItemDataPengguna;
    private javax.swing.JMenuItem MenuItemLogOut;
    private javax.swing.JMenuItem MenuItemSatuanBarang;
    private javax.swing.JMenuItem MenuItemStokBarang;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTextField txtKd_Satuan;
    private javax.swing.JTextField txtSatuan;
    // End of variables declaration//GEN-END:variables
}
